config/routes.rb
BankProduct::Application.routes.draw do
  
  match '/signin', to: 'sign_ins#new'
  match '/signout', to: 'sign_ins#destroy'
  resources :sign_ins, only: [:new, :create, :destroy]
  resources :users
  match '/signup', to: 'users#new'

  match '/credit_cards', to: 'credit_cards#index'

  get "shopping_districts/new"

  match '/home', to: 'static_pages#home'

  match '/about', to: 'static_pages#about'

  match '/contact', to: 'static_pages#contact'

  root to: 'static_pages#home'

  resources :banks

  

end

app/models/bank.rb
# == Schema Information
#
# Table name: banks
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Bank < ActiveRecord::Base
  attr_accessible :name
  has_many :credit_cards
  has_many :promotions
end

app/models/branch.rb
# == Schema Information
#
# Table name: branches
#
#  id                   :integer          not null, primary key
#  name                 :string(255)
#  shop_id              :integer
#  shopping_district_id :integer
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#

class Branch < ActiveRecord::Base
  attr_accessible :name
  belongs_to :shop
  belongs_to :shopping_district
  has_many :promotions
end

app/models/credit_card.rb
# == Schema Information
#
# Table name: credit_cards
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  bank_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class CreditCard < ActiveRecord::Base
  attr_accessible :name
  belongs_to :bank
  has_many :promotions
end

app/models/promotion.rb
# == Schema Information
#
# Table name: promotions
#
#  id                :integer          not null, primary key
#  name              :string(255)
#  start_date        :date
#  end_date          :date
#  content           :text
#  shop_id           :integer
#  branch_id         :integer
#  promotion_type_id :integer
#  credit_card_id    :integer
#  bank_id           :integer
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#

class Promotion < ActiveRecord::Base
  attr_accessible :content, :end_date, :name, :start_date
  belongs_to :shop
  belongs_to :credit_card
  belongs_to :promotion_type
  belongs_to :branch 
  belongs_to :bank
end

app/models/promotion_type.rb
# == Schema Information
#
# Table name: promotion_types
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class PromotionType < ActiveRecord::Base
  attr_accessible :name
  has_many :promotions
end

app/models/shop.rb
# == Schema Information
#
# Table name: shops
#
#  id               :integer          not null, primary key
#  name             :string(255)
#  shop_category_id :integer
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class Shop < ActiveRecord::Base
  attr_accessible :name
  belongs_to :shop_category
  has_many :branches
  has_many :promotions
end

app/models/shop_category.rb
# == Schema Information
#
# Table name: shop_categories
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class ShopCategory < ActiveRecord::Base
  attr_accessible :name
  has_many :shops
end

app/models/shopping_district.rb
# == Schema Information
#
# Table name: shopping_districts
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class ShoppingDistrict < ActiveRecord::Base
  attr_accessible :name
  has_many :branches
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  password_digest :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation, :user_type
  has_secure_password

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  before_save do |user|
  	user.email = email.downcase
  end

  validates :email, presence: true, 
  			length: {maximum: 50}, uniqueness: {case_sensitive: false},
  			format: {with: VALID_EMAIL_REGEX}
  validates :name, presence: true
  validates :password, presence: true, length: {minimum: 6}
  validates :password_confirmation, presence: true, length: {minimum: 6}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  
end

app/controllers/banks_controller.rb
class BanksController < ApplicationController
	def new
		@bank = Bank.new
	end
end

app/controllers/sign_ins_controller.rb
class SignInsController < ApplicationController
  def new

  end

  def create
  	user = User.find_by_email(params[:sign_in][:email].downcase)
  	if user && user.authenticate(params[:sign_in][:password])
  		session[:current_user] = user
  		redirect_to home_path
  	else
  		flash.now[:error] = "email or password error!"
  		render 'new'
  	end
  end

  def destroy
  	session[:current_user] = nil
  	redirect_to home_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(params[:user])
    
  	if @user.save then
      
      current_user = User.find(@user.id)
      session[:current_user] = @user
  		redirect_to home_path
  	else
      flash.now[:error] = @user.errors.full_messages.first
      render 'new'
  	end 
  end

  def index
  end

  def destroy
    session[:current_user_id] = nil
    current_user = nil
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/banks_helper.rb
module BanksHelper
end

app/helpers/credit_cards_helper.rb
module CreditCardsHelper
end

app/helpers/shopping_districts_helper.rb
module ShoppingDistrictsHelper
end

app/helpers/sign_ins_helper.rb
module SignInsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navigation_bar.html.erb
<div class="row-fluid" style="margin-top:10px">
	<div class="navbar">
		<div class="navbar-inner">
			<div class="container">
				<a class="btn btn-navbar" data-toggle="collapse" data-target=".navbar-responsive-collapse">
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			    </a>
			    <div class="nav-collapse collapse navbar-responsive-collapse">
			    	<ul class="nav">
						<li><a href="#">最新</a></li>
						<li><a href="#">推荐</a></li>
						<li><a href="#">银行</a></li>
						<li><a href="#">商家</a></li>
					</ul>	
					<form class="navbar-search pull-left" action>
						<input type="text" class="search-query">
					</form>
			    </div>

				
			</div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <style type="text/css">
  	body{
  		padding-top: 10px;
  		padding-bottom: 40px;
  	}

  	/* Customize the navbar links to be fill the entire space of the .navbar */
	.navbar .navbar-inner {
		padding: 0;
	}
	.navbar .nav {
		margin: 0;
		display: table;
		width: 100%;
	}
	.navbar .nav li {
		display: table-cell;
		width: 1%;
		float: none;
	}
	.navbar .nav li a {
		font-weight: bold;
		text-align: center;
		border-left: 1px solid rgba(255,255,255,.75);
		border-right: 1px solid rgba(0,0,0,.1);
	}
	.navbar .nav li:first-child a {
		border-left: 0;
		border-radius: 3px 0 0 3px;
	}
	.navbar .nav li:last-child a {
		border-right: 0;
		border-radius: 0 3px 3px 0;
	}
  </style>
</head>
<body>
	<div class="container">
		<div class="row-fluid">
			<div class="masthead">
				<ul class="nav nav-pills pull-right">
					<%if session[:current_user] == nil then %>
						<li><%= link_to "登录", signin_path%></li>
						<li><%= link_to "注册", signup_path%></li>
					<%else%>
						<li><%= link_to "退出", signout_path%></li>
					<%end%>
				</ul>
				<h2>
					<%= link_to image_tag("logo.png", height: 60, width: 135), root_path %>
					<small class="text-success">
						卡悠－最贴心的信用卡优惠信息
					</small>
				</h2>

			</div>
		</div>
		
		<%= yield %>
		
		<hr>
		<footer class="row-fuild text-center">
			<p class="text-center">
				Company 2013
				<%= link_to "关于", about_path, class: "btn-link"%>
				<%= link_to "联系我们", contact_path, class: "btn-link"%>
			</p>
			<p>
				<%= debug(params) if Rails.env.development? %>
			</p>
		</footer>
	</div>
</body>
</html>